/**
 * Cloudflare Colo (Data Center) to City Mapping
 * Maps IATA airport codes to city names
 * Last updated: 2026-02-07
 */

export const COLO_TO_CITY: Record<string, string> = {
  // Africa
  'ACC': 'Accra, Ghana',
  'ALG': 'Algiers, Algeria',
  'AAE': 'Annaba, Algeria',
  'TNR': 'Antananarivo, Madagascar',
  'CPT': 'Cape Town, South Africa',
  'DKR': 'Dakar, Senegal',
  'DAR': 'Dar Es Salaam, Tanzania',
  'JIB': 'Djibouti City, Djibouti',
  'DUR': 'Durban, South Africa',
  'GBE': 'Gaborone, Botswana',
  'HRE': 'Harare, Zimbabwe',
  'JNB': 'Johannesburg, South Africa',
  'KGL': 'Kigali, Rwanda',
  'LOS': 'Lagos, Nigeria',
  'LAD': 'Luanda, Angola',
  'MPM': 'Maputo, Mozambique',
  'MBA': 'Mombasa, Kenya',
  'NBO': 'Nairobi, Kenya',
  'ORN': 'Oran, Algeria',
  'OUA': 'Ouagadougou, Burkina Faso',
  'MRU': 'Port Louis, Mauritius',
  'TUN': 'Tunis, Tunisia',
  'FIH': 'Kinshasa, DR Congo',
  'CAI': 'Cairo, Egypt',
  'WDH': 'Windhoek, Namibia',
  'ASK': 'Yamoussoukro, Ivory Coast',
  'ABJ': 'Abidjan, Ivory Coast',
  'EBB': 'Kampala, Uganda',
  'RUN': 'Saint-Denis, Réunion',
  'LUN': 'Lusaka, Zambia',
  'ADD': 'Addis Ababa, Ethiopia',
  'LLW': 'Lilongwe, Malawi',
  'CZL': 'Constantine, Algeria',

  // Asia
  'AMD': 'Ahmedabad, India',
  'ALA': 'Almaty, Kazakhstan',
  'BLR': 'Bangalore, India',
  'BKK': 'Bangkok, Thailand',
  'BWN': 'Bandar Seri Begawan, Brunei',
  'CEB': 'Cebu, Philippines',
  'IXC': 'Chandigarh, India',
  'CGD': 'Changde, China',
  'MAA': 'Chennai, India',
  'CGP': 'Chittagong, Bangladesh',
  'CMB': 'Colombo, Sri Lanka',
  'DAC': 'Dhaka, Bangladesh',
  'FUO': 'Foshan, China',
  'FUK': 'Fukuoka, Japan',
  'FOC': 'Fuzhou, China',
  'CAN': 'Guangzhou, China',
  'HAK': 'Haikou, China',
  'HAN': 'Hanoi, Vietnam',
  'SJW': 'Hengshui, China',
  'SGN': 'Ho Chi Minh City, Vietnam',
  'HKG': 'Hong Kong',
  'HYD': 'Hyderabad, India',
  'ISB': 'Islamabad, Pakistan',
  'CGK': 'Jakarta, Indonesia',
  'TNA': 'Jinan, China',
  'JHB': 'Johor Bahru, Malaysia',
  'KNU': 'Kanpur, India',
  'KHH': 'Kaohsiung City, Taiwan',
  'KHI': 'Karachi, Pakistan',
  'KTM': 'Kathmandu, Nepal',
  'CCU': 'Kolkata, India',
  'KJA': 'Krasnoyarsk, Russia',
  'KUL': 'Kuala Lumpur, Malaysia',
  'PKX': 'Langfang, China',
  'MFM': 'Macau',
  'MLE': 'Malé, Maldives',
  'MNL': 'Manila, Philippines',
  'BOM': 'Mumbai, India',
  'NAG': 'Nagpur, India',
  'OKA': 'Naha, Japan',
  'DEL': 'New Delhi, India',
  'KIX': 'Osaka, Japan',
  'PAT': 'Patna, India',
  'PNH': 'Phnom Penh, Cambodia',
  'TAO': 'Qingdao, China',
  'ICN': 'Seoul, South Korea',
  'SHA': 'Shanghai, China',
  'SIN': 'Singapore',
  'URT': 'Surat Thani, Thailand',
  'TPE': 'Taipei',
  'NRT': 'Tokyo, Japan',
  'ULN': 'Ulaanbaatar, Mongolia',
  'VTE': 'Vientiane, Laos',
  'KHN': 'Xinyu, China',
  'EVN': 'Yerevan, Armenia',
  'JOG': 'Yogyakarta, Indonesia',
  'CGY': 'Cagayan de Oro, Philippines',
  'COK': 'Kochi, India',
  'DPS': 'Denpasar, Indonesia',
  'CNN': 'Kannur, India',
  'SZX': 'Shenzhen, China',
  'KWE': 'Guiyang, China',
  'HGH': 'Shaoxing, China',
  'CZX': 'Changzhou, China',
  'KMG': 'Kunming, China',
  'CNX': 'Chiang Mai, Thailand',
  'CGO': 'Zhengzhou, China',
  'TYN': 'Yangquan, China',
  'CSX': 'Changsha, China',
  'DLC': 'Dalian, China',
  'BHY': 'Beihai, China',
  'CKG': 'Chongqing, China',
  'XFN': 'Xiangyang, China',
  'DAD': 'Da Nang, Vietnam',
  'JXG': 'Jiaxing, China',
  'CRK': 'Tarlac City, Philippines',
  'PBH': 'Thimphu, Bhutan',
  'XIY': 'Baoji, China',
  'NQZ': 'Astana, Kazakhstan',
  'KCH': 'Kuching, Malaysia',
  'AKX': 'Aktobe, Kazakhstan',
  'TEN': 'Tongren, China',
  'HYN': 'Taizhou, China',
  'XNN': 'Xining, China',
  'FRU': 'Bishkek, Kyrgyzstan',
  'MLG': 'Malang, Indonesia',
  'LHE': 'Lahore, Pakistan',
  'CTU': 'Chengdu, China',
  'AGR': 'Agra, India',
  'CJB': 'Coimbatore, India',

  // Europe
  'AMS': 'Amsterdam, Netherlands',
  'ATH': 'Athens, Greece',
  'BCN': 'Barcelona, Spain',
  'BEG': 'Belgrade, Serbia',
  'TXL': 'Berlin, Germany',
  'BOD': 'Bordeaux, France',
  'BTS': 'Bratislava, Slovakia',
  'BRU': 'Brussels, Belgium',
  'OTP': 'Bucharest, Romania',
  'BUD': 'Budapest, Hungary',
  'KIV': 'Chișinău, Moldova',
  'CPH': 'Copenhagen, Denmark',
  'DUB': 'Dublin, Ireland',
  'DUS': 'Düsseldorf, Germany',
  'FRA': 'Frankfurt, Germany',
  'GVA': 'Geneva, Switzerland',
  'GOT': 'Gothenburg, Sweden',
  'HAM': 'Hamburg, Germany',
  'HEL': 'Helsinki, Finland',
  'IST': 'Istanbul, Turkey',
  'ADB': 'Izmir, Turkey',
  'KBP': 'Kyiv, Ukraine',
  'LIS': 'Lisbon, Portugal',
  'LHR': 'London, United Kingdom',
  'LUX': 'Luxembourg City, Luxembourg',
  'LYS': 'Lyon, France',
  'MAD': 'Madrid, Spain',
  'MAN': 'Manchester, United Kingdom',
  'MRS': 'Marseille, France',
  'MXP': 'Milan, Italy',
  'MSQ': 'Minsk, Belarus',
  'DME': 'Moscow, Russia',
  'MUC': 'Munich, Germany',
  'LCA': 'Nicosia, Cyprus',
  'OSL': 'Oslo, Norway',
  'PMO': 'Palermo, Italy',
  'CDG': 'Paris, France',
  'PRG': 'Prague, Czech Republic',
  'KEF': 'Reykjavík, Iceland',
  'RIX': 'Riga, Latvia',
  'FCO': 'Rome, Italy',
  'LED': 'Saint Petersburg, Russia',
  'MLA': 'Santa Venera, Malta',
  'SKP': 'Skopje, North Macedonia',
  'SOF': 'Sofia, Bulgaria',
  'ARN': 'Stockholm, Sweden',
  'STR': 'Stuttgart, Germany',
  'TLL': 'Tallinn, Estonia',
  'TBS': 'Tbilisi, Georgia',
  'SKG': 'Thessaloniki, Greece',
  'TIA': 'Tirana, Albania',
  'VIE': 'Vienna, Austria',
  'VNO': 'Vilnius, Lithuania',
  'WAW': 'Warsaw, Poland',
  'WRO': 'Wroclaw, Poland',
  'ZAG': 'Zagreb, Croatia',
  'ZRH': 'Zurich, Switzerland',

  // Latin America & the Caribbean
  'QWJ': 'Americana, Brazil',
  'ARI': 'Arica, Chile',
  'ASU': 'Asunción, Paraguay',
  'BEL': 'Belém, Brazil',
  'CNF': 'Belo Horizonte, Brazil',
  'BNU': 'Blumenau, Brazil',
  'BOG': 'Bogotá, Colombia',
  'BSB': 'Brasilia, Brazil',
  'EZE': 'Buenos Aires, Argentina',
  'CFC': 'Caçador, Brazil',
  'VCP': 'Campinas, Brazil',
  'COR': 'Córdoba, Argentina',
  'CWB': 'Curitiba, Brazil',
  'FLN': 'Florianopolis, Brazil',
  'FOR': 'Fortaleza, Brazil',
  'GEO': 'Georgetown, Guyana',
  'GYN': 'Goiânia, Brazil',
  'GUA': 'Guatemala City, Guatemala',
  'GYE': 'Guayaquil, Ecuador',
  'JOI': 'Joinville, Brazil',
  'JDO': 'Juazeiro do Norte, Brazil',
  'LIM': 'Lima, Peru',
  'MAO': 'Manaus, Brazil',
  'MDE': 'Medellín, Colombia',
  'NQN': 'Neuquén, Argentina',
  'PTY': 'Panama City, Panama',
  'PBM': 'Paramaribo, Suriname',
  'POA': 'Porto Alegre, Brazil',
  'UIO': 'Quito, Ecuador',
  'REC': 'Recife, Brazil',
  'RAO': 'Ribeirao Preto, Brazil',
  'GIG': 'Rio de Janeiro, Brazil',
  'SJO': 'San José, Costa Rica',
  'SCL': 'Santiago, Chile',
  'SDQ': 'Santo Domingo, Dominican Republic',
  'SJP': 'São José do Rio Preto, Brazil',
  'SJK': 'São José dos Campos, Brazil',
  'GRU': 'São Paulo, Brazil',
  'SOD': 'Sorocaba, Brazil',
  'TGU': 'Tegucigalpa, Honduras',
  'NVT': 'Timbó, Brazil',
  'UDI': 'Uberlândia, Brazil',
  'VIX': 'Vitoria, Brazil',
  'CAW': 'Campos dos Goytacazes, Brazil',
  'XAP': 'Chapeco, Brazil',
  'BGI': 'Bridgetown, Barbados',
  'GND': "St. George's, Grenada",
  'STI': 'Santiago de los Caballeros, Dominican Republic',
  'LPB': 'La Paz, Bolivia',
  'SJU': 'San Juan, Puerto Rico',
  'BAQ': 'Barranquilla, Colombia',
  'PMW': 'Palmas, Brazil',
  'ARU': 'Aracatuba, Brazil',
  'POS': 'Port of Spain, Trinidad and Tobago',
  'SSA': 'Salvador, Brazil',
  'CGB': 'Cuiaba, Brazil',
  'CLO': 'Cali, Colombia',
  'SAP': 'San Pedro Sula, Honduras',
  'CCP': 'Concepción, Chile',

  // Middle East
  'AMM': 'Amman, Jordan',
  'LLK': 'Astara, Azerbaijan',
  'BGW': 'Baghdad, Iraq',
  'GYD': 'Baku, Azerbaijan',
  'BSR': 'Basra, Iraq',
  'BEY': 'Beirut, Lebanon',
  'DMM': 'Dammam, Saudi Arabia',
  'DOH': 'Doha, Qatar',
  'DXB': 'Dubai, United Arab Emirates',
  'EBL': 'Erbil, Iraq',
  'HFA': 'Haifa, Israel',
  'JED': 'Jeddah, Saudi Arabia',
  'KWI': 'Kuwait City, Kuwait',
  'BAH': 'Manama, Bahrain',
  'MCT': 'Muscat, Oman',
  'NJF': 'Najaf, Iraq',
  'XNH': 'Nasiriyah, Iraq',
  'ZDM': 'Ramallah',
  'RUH': 'Riyadh, Saudi Arabia',
  'ISU': 'Sulaymaniyah, Iraq',
  'TLV': 'Tel Aviv, Israel',

  // North America
  'ABQ': 'Albuquerque, NM',
  'ANC': 'Anchorage, AK',
  'IAD': 'Ashburn, VA',
  'ATL': 'Atlanta, GA',
  'AUS': 'Austin, TX',
  'BGR': 'Bangor, ME',
  'BOS': 'Boston, MA',
  'BUF': 'Buffalo, NY',
  'YYC': 'Calgary, AB',
  'CLT': 'Charlotte, NC',
  'ORD': 'Chicago, IL',
  'CLE': 'Cleveland, OH',
  'CMH': 'Columbus, OH',
  'DFW': 'Dallas, TX',
  'DEN': 'Denver, CO',
  'DTW': 'Detroit, MI',
  'RDU': 'Durham, NC',
  'GDL': 'Guadalajara, Mexico',
  'YHZ': 'Halifax, Canada',
  'HNL': 'Honolulu, HI',
  'IAH': 'Houston, TX',
  'IND': 'Indianapolis, IN',
  'JAX': 'Jacksonville, FL',
  'MCI': 'Kansas City, MO',
  'KIN': 'Kingston, Jamaica',
  'LAS': 'Las Vegas, NV',
  'LAX': 'Los Angeles, CA',
  'MEM': 'Memphis, TN',
  'MEX': 'Mexico City, Mexico',
  'MIA': 'Miami, FL',
  'MSP': 'Minneapolis, MN',
  'YUL': 'Montréal, QC',
  'BNA': 'Nashville, TN',
  'EWR': 'Newark, NJ',
  'ORF': 'Norfolk, VA',
  'OKC': 'Oklahoma City, OK',
  'OMA': 'Omaha, NE',
  'YOW': 'Ottawa, Canada',
  'PHL': 'Philadelphia, PA',
  'PHX': 'Phoenix, AZ',
  'PIT': 'Pittsburgh, PA',
  'PDX': 'Portland, OR',
  'QRO': 'Queretaro, Mexico',
  'RIC': 'Richmond, VA',
  'SMF': 'Sacramento, CA',
  'SLC': 'Salt Lake City, UT',
  'SAT': 'San Antonio, TX',
  'SAN': 'San Diego, CA',
  'SFO': 'San Francisco, CA',
  'SJC': 'San Jose, CA',
  'YXE': 'Saskatoon, SK',
  'SEA': 'Seattle, WA',
  'FSD': 'Sioux Falls, SD',
  'STL': 'St. Louis, MO',
  'TLH': 'Tallahassee, FL',
  'TPA': 'Tampa, FL',
  'YYZ': 'Toronto, ON',
  'YVR': 'Vancouver, BC',
  'YWG': 'Winnipeg, MB',

  // Oceania
  'AKL': 'Auckland, New Zealand',
  'BNE': 'Brisbane, Australia',
  'CHC': 'Christchurch, New Zealand',
  'GUM': 'Hagåtña, Guam',
  'MEL': 'Melbourne, Australia',
  'NAN': 'Nadi, Fiji',
  'NOU': 'Nouméa, New Caledonia',
  'PER': 'Perth, Australia',
  'PPT': 'Papeete, French Polynesia',
  'SYD': 'Sydney, Australia',
};

/**
 * Get city name from IATA colo code
 */
export function getColoCity(colo: string | undefined): string {
  if (!colo) return '';
  return COLO_TO_CITY[colo.toUpperCase()] || '';
}
